name: JavaScript Tests

on: [ push ]

jobs:
    test:
        name: JavaScript Tests
        runs-on: ubuntu-latest
        steps:
            # ---------- Checkout ---------- #

            -   name: Checkout
                uses: actions/checkout@v3

            # ---------- Setup Environment ---------- #

            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 17.9.1
                    cache: 'npm'

            # ---------- Install ---------- #

            -   name: Install Dependencies
                run: npm install

            # ---------- Test ---------- #

            -   name: Run Unit Tests
                run: npm test -- --lang=js
